### ISSUE TITLE
You just broke the jquery dependency

### ISSUE THREAD

**Issue by kaushieksingh** [fitodac/bsnav#10]
This was running alright 2 days ago. Since you've made changes to js files, it is now dependent on older jquery versions. As BS4 recommends jquery 3.3 in their copy paste codes, consider upgrading the js to version jquery 3.3.

Specifically .indexof and .load functions needs to be handled.

**Comment by fitodac** [comment]
Hi.
Thanks for your collaboration.
I will try to fix this asasp.
regards.

**Comment by waitforit** [comment]
I think you just need to change "n(window).load(function() "  to "n(window).on('load',function() "

**Comment by fitodac** [comment]
I made the change as the @waitforit comment.
Please, confirm if this was fixed.
Regards.

**Comment by kaushieksingh** [comment]
Done. Thanks.
