### ISSUE TITLE
Submenu dropdown's class: .nav-item.dropdown>.navbar-nav.in

### ISSUE THREAD

**Issue by sheralimuzaffarov** [fitodac/bsnav#12]
in bsnav.css code:
.nav-item.dropdown>.navbar-nav.in {
    pointer-events: initial;
    clip: rect(0,50vw,2000px,0);
    transition: 1.5s ease-in;
}
but it's cropping like this:
![Снимок](https://user-images.githubusercontent.com/35257303/70218578-06b6cb00-1765-11ea-973c-773289a7054d.PNG)
I changed clip property and then it worked:
.nav-item.dropdown>.navbar-nav.in {
        clip: rect(0,100vw,2000px,0); // or (clip: unset;)
 }
My question: why clip property is needed here?

**Comment by fitodac** [comment]
Clip is used to show animations for submenus with css instead javascript
