### ISSUE TITLE
Feature Request: auto-adjust left/right submenus

### ISSUE THREAD

**Issue by Rombecchi** [fitodac/bsnav#13]
Hi, I have a menu that is generated programmatically by the software and it is impossible to know if a submenu item should require a "dropdown-right". 
Also, if a standard drop-down menu item with some submenus is located at the end of the menu, they overflow the document and the scrollbars appear in the window. 
Look at this: https://codepen.io/Rombecchi/pen/eYmmqKV : a scrollbar appears in the desktop view because the third option has many submenus.
It would be great if a function could check if some dropdown items needed a "dropdown-right" class to add. 
Thinking of multiple submenus should support multiple alignment (such as: left-right-left-left-right-right).

**Comment by fitodac** [comment]
Usually I check if the "current item" is the last item in the menu. It's a silly solution, but usaually works.
Other way, you need to calculate if the submenu is out of the viewport to add/change the submenu class to show it at the right.
... 

Bsnav is conceived as an html/css menu.

We add the small javascript for some additional features that can't be added without it.
We're not able to add the functionality you need, but when you solve it, feel free to do a pull request to the repo for other users.
We appreciate your help to continue making great this menu.

**Comment by fitodac** [comment]
Please, check again the [codepen]( https://codepen.io/Rombecchi/pen/eYmmqKV), I write some javascript hoping to help you.

regards

**Comment by Rombecchi** [comment]
Thank you very much, I can't see any change in my codepen but I'll try to solve it by myself.
See you!
