### ISSUE TITLE
side nav not opening on Button Click

### ISSUE THREAD

**Issue by raptorage527** [fitodac/bsnav#5]
i have implemented this exactly as said and I couldn't get it to work. The menu button works but on click the sidenav wont open and the styling for the navigation is not applied.

**Comment by fitodac** [comment]
Hi @raptorage527,
could you provide me a link?
thanks

**Comment by raptorage527** [comment]
I can't at the moment. but if you can tell me where to add the links it would be helpful. I know there is a section which says where to add them. But here is what i did i've put the bsnav.min.js in the head below bootstrap.min.css and bsnav.min.js before the closing body tag of my html file. This is usually how i load any external script files. oh by the way i have loaded the minified files from the dist folder.

**Comment by fitodac** [comment]
Sorry,
I need to finish the documentation yet. I'm verry bussy this days.
Please add the following to the end of the `<body>`

`<div class="bsnav-mobile">`
`<div class="bsnav-mobile-overlay">`
`<div class="navbar"></div>`
`</div>`
`</div>`

and please, let me know if this helps.

**Comment by raptorage527** [comment]
yes it is working Fine Now. Thank you soo much for the quick response.

**Comment by fitodac** [comment]
Thanks for use bsnav!!
regards
